Vagrant.configure("2") do |config|
  config.vm.define "apache1" do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.synced_folder"/home/devops/myvagrants/php-apache","/vagrant",disabled:false
end
  
   config.vm.define "apache2" do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8082
  config.vm.synced_folder"/home/devops/myvagrants/php-apache","/vagrant",disabled:false
end

config.vm.define "apache3" do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8083
  config.vm.synced_folder"/home/devops/myvagrants/php-apache","/vagrant",disabled:false
end

config.vm.define "apache4" do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 8084
  config.vm.synced_folder"/home/devops/myvagrants/php-apache","/vagrant",disabled:false
end
end
