  - name: "crear grupo operador"
    become: yes 
    group:
      name: operador
      state: present
    become: yes

  - name: "Create user accounts"
    user:
      name: "{{ item }}"
      groups: "operador"
    with_items: "{{ users }}"
    become: yes

  - name: "Add authorized keys"
    authorized_key:
      user: "{{ item }}"
      key: "{{ lookup('file', '{{ role_path }}/files/{{item}}.pub') }}"
    with_items: "{{ users }}"
    become: yes

  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "^%operador"
      line: "%operador ALL=(ALL) NOPASSWD: ALL"
    become: yes
