- hosts: all
  sudo: true
  tasks:
   - name: updates a server
     apt: update_cache=yes
   - name: upgrade a server
     apt: upgrade=dist  
   - name: Install apache httpd but avoid starting it immediately (state=present is optional)
     apt: name=apache2 update_cache=yes state=latest

