- hosts: all
  sudo: true
  tasks:
   - name: updates a server
     yum: update_cache=yes
   - name: upgrade a server
     yum: upgrade=dist  
   - name: Install apache httpd but avoid starting it immediately (state=present is optional)
     yum: name=apache2 update_cache=yes state=latest

